module.exports = {
    restaurants: [{
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807889066,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "",
                "description": "满20减2，满30减3，满40减8",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 282613058,
                "is_exclusive_with_food_activity": true,
                "name": "满减活动",
                "tips": "满20减2，满30减3，满40减8",
                "type": 102
            }],
            "address": "广州市天河区棠东棠德东路2号铺",
            "authentic_id": 1382787261439301,
            "description": "金早绿点，做广州人最喜爱的早餐。",
            "distance": 3529,
            "favored": false,
            "flavors": [{
                "id": 213,
                "name": "米粉面馆"
            }],
            "float_delivery_fee": 5.5,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 147011301,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.131713,
            "longitude": 113.387724,
            "max_applied_quantity_per_order": -1,
            "name": "金早绿点(棠东店)",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["06:00/18:30"],
            "order_lead_time": 40,
            "phone": "18520408765 020-23358788",
            "piecewise_agent_fee": {
                "description": "配送费¥5.5",
                "extra_fee": 2.5,
                "is_extra": true,
                "rules": [{
                    "fee": 5.5,
                    "price": 20
                }],
                "tips": "配送费¥5.5"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "金早绿点，做广州人最喜爱的早点，我们在这里等您",
            "rating": 4.8,
            "rating_count": 0,
            "recent_order_num": 412,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=147011301",
            "status": 1,
            "support_tags": [],
            "supports": [{
                "description": "该商户食品安全已由中国太平洋保险承保，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "two_characters_icon_name": "保险"
            }],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 1037246890,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "",
                "description": "满50减25，满100减50，满200减100",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1023493521,
                "is_exclusive_with_food_activity": true,
                "name": "自营销复杂满减活动",
                "tips": "满50减25，满100减50，满200减100",
                "type": 102
            }, {
                "description": "皮皮虾",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 372573074,
                "name": "皮皮虾",
                "tips": "皮皮虾"
            }, {
                "description": "新鲜海鲜半价等你来品尝",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 367825082,
                "name": "新鲜海鲜半价等你来品尝",
                "tips": "新鲜海鲜半价等你来品尝"
            }, {
                "description": "新店一折秒杀",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 367824586,
                "name": "新店一折秒杀",
                "tips": "新店一折秒杀"
            }, {
                "description": "特价小龙虾",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 367823530,
                "name": "特价小龙虾",
                "tips": "特价小龙虾"
            }, {
                "description": "下单可返10元代金券",
                "icon_color": "ff7239",
                "icon_name": "返",
                "id": -1,
                "name": "下单返代金券",
                "tips": "下单可返10元代金券"
            }],
            "address": "广州市天河区员村田心路自编25号一楼160号",
            "authentic_id": 7382747247832646,
            "closing_count_down": 0,
            "description": "",
            "distance": 3937,
            "favored": false,
            "flavors": [{
                "id": 236,
                "name": "小龙虾"
            }, {
                "id": 218,
                "name": "烧烤"
            }],
            "float_delivery_fee": 20,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 146252146,
            "image_path": "r1.webp",
            "is_new": true,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.116222,
            "longitude": 113.358279,
            "max_applied_quantity_per_order": -1,
            "name": "非常虾小龙虾外卖",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/06:00"],
            "order_lead_time": 39,
            "phone": "13428885308",
            "piecewise_agent_fee": {
                "description": "配送费¥20",
                "extra_fee": 0,
                "is_extra": false,
                "rules": [{
                    "fee": 20,
                    "price": 20
                }],
                "tips": "配送费¥20"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "",
            "rating": 5,
            "rating_count": 0,
            "recent_order_num": 327,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=146252146",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商户食品安全已由中国太平洋保险承保，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "two_characters_icon_name": "保险"
            }, {
                "description": "该商家支持开发票，开票订单金额150元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 806171738,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "",
                "description": "满30减15，满40减30，满81减40",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 890097713,
                "is_exclusive_with_food_activity": true,
                "name": "自营销复杂满减活动",
                "tips": "满30减15，满40减30，满81减40",
                "type": 102
            }, {
                "attribute": "",
                "description": "满80元赠送日式抹茶奶茶1份",
                "icon_color": "3cc791",
                "icon_name": "赠",
                "id": 373227242,
                "is_exclusive_with_food_activity": true,
                "name": "满立赠",
                "tips": "满80元赠送日式抹茶奶茶1份",
                "type": 106
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 357226146,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "6折夜宵",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 351332346,
                "name": "6折夜宵",
                "tips": "6折夜宵"
            }, {
                "description": "周末5折早餐",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 341010834,
                "name": "周末5折早餐",
                "tips": "周末5折早餐"
            }],
            "address": "广州市天河区棠东丰乐肉菜综合市场J1号铺",
            "authentic_id": 3352707257368631,
            "description": "",
            "distance": 3136,
            "favored": false,
            "flavors": [{
                "id": 234,
                "name": "炸鸡炸串"
            }, {
                "id": 237,
                "name": "地方小吃"
            }],
            "float_delivery_fee": 4,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 161080931,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.12887,
            "longitude": 113.383428,
            "max_applied_quantity_per_order": -1,
            "name": "嘎嘎香e家小吃",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["00:00/24:00"],
            "order_lead_time": 44,
            "phone": "13725170832",
            "piecewise_agent_fee": {
                "description": "配送费¥4",
                "extra_fee": 1,
                "is_extra": true,
                "rules": [{
                    "fee": 4,
                    "price": 20
                }],
                "tips": "优惠配送费¥4"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "嘎嘎香炸鸡欢迎您，很高兴为大家服务",
            "rating": 4.6,
            "rating_count": 0,
            "recent_order_num": 162,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161080931",
            "status": 1,
            "support_tags": [],
            "supports": [{
                "description": "该商户食品安全已由中国太平洋保险承保，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "two_characters_icon_name": "保险"
            }],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 971447129,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "",
                "description": "满15减14，满20减16，满35减20，满50减25，满70减30",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1034536465,
                "is_exclusive_with_food_activity": true,
                "name": "自营销复杂满减活动",
                "tips": "满15减14，满20减16，满35减20，满50减25，满70减30",
                "type": 102
            }, {
                "description": "9.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 373892914,
                "name": "9.9",
                "tips": "9.9"
            }, {
                "description": "9.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 373574642,
                "name": "9.9",
                "tips": "9.9"
            }, {
                "description": "9.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 373511794,
                "name": "9.9",
                "tips": "9.9"
            }, {
                "description": "16.8",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 370576258,
                "name": "16.8",
                "tips": "16.8"
            }, {
                "description": "15.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 370575370,
                "name": "15.9",
                "tips": "15.9"
            }, {
                "description": "小菜",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 367832794,
                "name": "小菜",
                "tips": "小菜"
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 361190546,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 361188858,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "12.9元区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 352463786,
                "name": "12.9元区",
                "tips": "12.9元区"
            }, {
                "description": "小馄饨9.9元区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 352463034,
                "name": "小馄饨9.9元区",
                "tips": "小馄饨9.9元区"
            }, {
                "description": "八宝粥特价区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 351795370,
                "name": "八宝粥特价区",
                "tips": "八宝粥特价区"
            }, {
                "description": "小菜2.5元区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 351761114,
                "name": "小菜2.5元区",
                "tips": "小菜2.5元区"
            }, {
                "description": "小馄饨13.9元区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 351752682,
                "name": "小馄饨13.9元区",
                "tips": "小馄饨13.9元区"
            }, {
                "description": "饮料低至 1元",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 351315378,
                "name": "饮料低至 1元",
                "tips": "饮料低至 1元"
            }, {
                "description": "面 粉 9.9元来袭",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 349756522,
                "name": "面 粉 9.9元来袭",
                "tips": "面 粉 9.9元来袭"
            }, {
                "description": "小菜加料区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 349755786,
                "name": "小菜加料区",
                "tips": "小菜加料区"
            }, {
                "description": "小菜特价区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 349755106,
                "name": "小菜特价区",
                "tips": "小菜特价区"
            }, {
                "description": "饮料特价区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 349754682,
                "name": "饮料特价区",
                "tips": "饮料特价区"
            }, {
                "description": "饮料区特价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 349754354,
                "name": "饮料区特价",
                "tips": "饮料区特价"
            }, {
                "description": "特价饮料区",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 349753810,
                "name": "特价饮料区",
                "tips": "特价饮料区"
            }],
            "address": "广州市天河区棠东东南路10号205C房",
            "authentic_id": 4322737253319588,
            "bidding": "",
            "description": "老上海吃得香馄饨王是一家百年传承老店，馄饨由精练千里香香料，精制调味肉馅和汤料组成。外观汤清澈，馄饨皮薄馅大，晶莹剔透，口感滑爽，入口清香。口口都是肉都是肉！！！",
            "distance": 2728,
            "favored": false,
            "flavors": [{
                "id": 217,
                "name": "饺子馄饨"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3.5,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 162239388,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.126206,
            "longitude": 113.386489,
            "max_applied_quantity_per_order": -1,
            "name": "老上海吃得香馄饨铺(棠东店)",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["07:00/02:40"],
            "order_lead_time": 41,
            "phone": "18102682912",
            "piecewise_agent_fee": {
                "description": "配送费¥3.5",
                "extra_fee": 0.5,
                "is_extra": true,
                "rules": [{
                    "fee": 3.5,
                    "price": 20
                }],
                "tips": "优惠配送费¥3.5"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "1.本店都是现煮的呦。馄饨馅带有海鲜（海鲜过敏者慎点）。 2.有任何问题联系18102682912哈。 3.欢迎亲们提供宝贵意见，咱们会全力以赴的。",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 4205,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": true,
                "reason": "广告",
                "track": ""
            },
            "recommend_reasons": [{
                "name": "味道超赞"
            }, {
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=162239388",
            "status": 1,
            "support_tags": [],
            "supports": [{
                "description": "该商户食品安全已由中国太平洋保险承保，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "two_characters_icon_name": "保险"
            }],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 805826042,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "",
                "description": "满23减10，满38减18，满58减26，满69减36",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1037954746,
                "is_exclusive_with_food_activity": true,
                "name": "满减",
                "tips": "满23减10，满38减18，满58减26，满69减36",
                "type": 102
            }, {
                "description": "【19.9】套餐特惠",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 368328226,
                "name": "【19.9】套餐特惠",
                "tips": "【19.9】套餐特惠"
            }, {
                "description": "【7折】套餐特惠",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 368328010,
                "name": "【7折】套餐特惠",
                "tips": "【7折】套餐特惠"
            }, {
                "description": "【8.5折】汤圆套餐",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 359074978,
                "name": "【8.5折】汤圆套餐",
                "tips": "【8.5折】汤圆套餐"
            }, {
                "description": "【7折】五行养生粥套餐",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 359074370,
                "name": "【7折】五行养生粥套餐",
                "tips": "【7折】五行养生粥套餐"
            }, {
                "description": "【9.9】酸辣四川米线",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 359073906,
                "name": "【9.9】酸辣四川米线",
                "tips": "【9.9】酸辣四川米线"
            }, {
                "description": "【19.9】重庆小面+凉虾+煎蛋",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 359072666,
                "name": "【19.9】重庆小面+凉虾+煎蛋",
                "tips": "【19.9】重庆小面+凉虾+煎蛋"
            }, {
                "description": "【19.9】抄手+冰粉+煎蛋",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 359072202,
                "name": "【19.9】抄手+冰粉+煎蛋",
                "tips": "【19.9】抄手+冰粉+煎蛋"
            }, {
                "description": "【4折】干豌杂米线+红豆沙",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 359071738,
                "name": "【4折】干豌杂米线+红豆沙",
                "tips": "【4折】干豌杂米线+红豆沙"
            }, {
                "description": "【4折】肥肠小面+绿豆沙",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 359071282,
                "name": "【4折】肥肠小面+绿豆沙",
                "tips": "【4折】肥肠小面+绿豆沙"
            }, {
                "description": "【5折】酸辣红薯粉",
                "icon_color": "f07373",
                "icon_name": "特",
                "id": 359070898,
                "name": "【5折】酸辣红薯粉",
                "tips": "【5折】酸辣红薯粉"
            }, {
                "description": "【9.9】销魂鸡丝面",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 359070450,
                "name": "【9.9】销魂鸡丝面",
                "tips": "【9.9】销魂鸡丝面"
            }, {
                "attribute": "2.0",
                "description": "本店新用户立减2元",
                "icon_color": "00b762",
                "icon_name": "新",
                "id": 359057610,
                "is_exclusive_with_food_activity": true,
                "name": "门店新客立减",
                "tips": "本店新用户立减2元",
                "type": 108
            }, {
                "description": "进店领3元代金券",
                "icon_color": "ffac2a",
                "icon_name": "领",
                "id": -1,
                "name": "到店领代金券",
                "tips": "进店领3元代金券"
            }],
            "address": "广州市天河区中山大道西491号首层",
            "authentic_id": 8342757256230777,
            "bidding": "",
            "description": "重庆家乡口味，只做家乡味道。所有香料原材料通通来自四川、重庆老家。只为从四川、重庆来广州打拼的游子送上一碗家乡小吃。回味家乡的味道，想家的时候你就来一碗。温馨提醒:为了高峰期不影亲们的用餐时间，亲们可以提前下预订单！",
            "distance": 2892,
            "favored": false,
            "flavors": [{
                "id": 213,
                "name": "米粉面馆"
            }, {
                "id": 217,
                "name": "饺子馄饨"
            }],
            "float_delivery_fee": 6,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 1918477,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.1261982222222,
            "longitude": 113.379021888889,
            "max_applied_quantity_per_order": -1,
            "name": "8勺抄手华师店(学院店)",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["09:00/23:00"],
            "order_lead_time": 31,
            "phone": "13659072798 13016026844",
            "piecewise_agent_fee": {
                "description": "配送费¥6",
                "extra_fee": 1,
                "is_extra": true,
                "rules": [{
                    "fee": 6,
                    "price": 20
                }],
                "tips": "配送费¥6"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "各位亲记得扫一扫二维码有本店的专属红包哦，本店优先配送网上订单，在此感谢小主们对本店一直以来的支持和信任，为了回馈小主们，我们坚持追求用心，责任，高品质，高效率，让小主们看到我们的努力，打心底觉得吃的安全，放心！温馨提醒:为了高峰期不影亲们的用餐时间，亲们可以提前下预订单！",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1041,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": true,
                "reason": "广告",
                "track": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }, {
                "name": "配送飞快"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=1918477",
            "status": 1,
            "support_tags": [],
            "supports": [{
                "description": "该商户食品安全已由中国太平洋保险承保，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "two_characters_icon_name": "保险"
            }],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 806310106,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "",
                "description": "满26减6",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 961759033,
                "is_exclusive_with_food_activity": true,
                "name": "自营销复杂满减活动",
                "tips": "满26减6",
                "type": 102
            }],
            "address": "广州市海珠区琶洲蟠龙新街1号21铺",
            "authentic_id": 8362757261838131,
            "description": "",
            "distance": 1394,
            "favored": false,
            "flavors": [{
                "id": 213,
                "name": "米粉面馆"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 2.5,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 155764631,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.098789,
            "longitude": 113.383349,
            "max_applied_quantity_per_order": -1,
            "name": "三叶肠粉(琶洲店)",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["07:30/20:45"],
            "order_lead_time": 29,
            "phone": "020-82321688",
            "piecewise_agent_fee": {
                "description": "配送费¥2.5",
                "extra_fee": 0,
                "is_extra": false,
                "rules": [{
                    "fee": 2.5,
                    "price": 20
                }],
                "tips": "配送费¥2.5"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "原香郁满肠店因品牌升级，目前已将店名更改我们为三叶肠粉店！我们的肠粉来自广东粤北山区，釆用家乡大米，现磨米浆现做。不添加任何化学元素，自然清香，爽滑可口，营养卫生，老少咸宜。",
            "rating": 4.6,
            "rating_count": 0,
            "recent_order_num": 289,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "配送飞快"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=155764631",
            "status": 1,
            "support_tags": [],
            "supports": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 803462754,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "",
                "description": "满30减16，满50减26，满70减36，满90减46",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 977557434,
                "is_exclusive_with_food_activity": true,
                "name": "满减",
                "tips": "满30减16，满50减26，满70减36，满90减46",
                "type": 102
            }],
            "address": "广州市天河区中山大道棠东村毓南路D幢8号",
            "authentic_id": 1352787242712776,
            "closing_count_down": 0,
            "description": "",
            "distance": 2951,
            "favored": false,
            "flavors": [{
                "id": 219,
                "name": "香锅砂锅"
            }],
            "float_delivery_fee": 4,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 159385276,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.12768,
            "longitude": 113.388074,
            "max_applied_quantity_per_order": -1,
            "name": "辣味坊麻辣香锅(棠东店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/14:00", "16:00/21:30"],
            "order_lead_time": 41,
            "phone": "18620251333",
            "piecewise_agent_fee": {
                "description": "配送费¥4",
                "extra_fee": 1,
                "is_extra": true,
                "rules": [{
                    "fee": 4,
                    "price": 20
                }],
                "tips": "配送费¥4"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "亲们本店单点不配米饭哦！欢迎光临辣味坊！我们揭诚为你服务!有什么意见请拔打我们电话哦！或备注！",
            "rating": 4.6,
            "rating_count": 0,
            "recent_order_num": 2646,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "味道超赞"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=159385276",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商户食品安全已由中国太平洋保险承保，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "two_characters_icon_name": "保险"
            }, {
                "description": "该商家支持开发票，开票订单金额200元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 807326418,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }],
            "address": "广州市天河区棠东毓南路D栋9号之一铺",
            "authentic_id": 3352707251086476,
            "closing_count_down": 0,
            "description": "泰好吃，不怕胖！！全国连锁品牌:沙哇低卡，专注健康西餐，轻食沙拉。让您因为健康美味而爱上沙哇低卡，而不是因为低卡而忍受我们！",
            "distance": 2974,
            "favored": false,
            "flavors": [{
                "id": 230,
                "name": "西餐"
            }, {
                "id": 265,
                "name": "简餐"
            }],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 10,
            "has_story": false,
            "id": 161186476,
            "image_path": "r1.webp",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 23.127833,
            "longitude": 113.388229,
            "max_applied_quantity_per_order": -1,
            "name": "沙哇低卡轻食沙拉(骏景金融城店)",
            "next_business_time": "10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/21:00"],
            "order_lead_time": 43,
            "phone": "18520560686",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": true,
                "rules": [{
                    "fee": 3,
                    "price": 10
                }],
                "tips": "优惠配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "满减特大优惠！！！ 39-25 49-30 59-35 69-40 79-45",
            "rating": 4.9,
            "rating_count": 0,
            "recent_order_num": 1538,
            "recommend": {
                "is_ad": false,
                "reason": ""
            },
            "recommend_reasons": [{
                "name": "回头客多"
            }],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=161186476",
            "status": 5,
            "support_tags": [],
            "supports": [{
                "description": "该商家支持开发票，开票订单金额100元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "type": 0
        }
    }],
    users: [{
        "name": "天下吃货",
        "phone": "123456789",
        "password": "e10adc3949ba59abbe56e057f20f883e",
        "payPwd": "e10adc3949ba59abbe56e057f20f883e",
        "avatar": "http://gw.alicdn.com/tps/i3/TB1K5xzLFXXXXb3aXXXbbw1QpXX-300-301.png"
    }],
    // orders: [{
    //     "id": 1,
    //     "user_id": 1,
    //     "restaurant_id": 147011301,
    //     "name": "神奇鸡翅",
    //     "price": 10,
    //     "image_path": "r1.webp",
    //     "selectNum": 1
    // }, {
    //     "id": 2,
    //     "user_id": 1,
    //     "restaurant_id": 147011301,
    //     "name": "黑暗料理",
    //     "price": 100,
    //     "image_path": "r1.webp",
    //     "selectNum": 1
    // }, {
    //     "id": 1,
    //     "user_id": 1,
    //     "restaurant_id": 147011302,
    //     "name": "神奇鸡翅",
    //     "price": 10,
    //     "image_path": "r1.webp",
    //     "selectNum": 1
    // }, {
    //     "id": 2,
    //     "user_id": 1,
    //     "restaurant_id": 147011302,
    //     "name": "黑暗料理",
    //     "price": 100,
    //     "image_path": "r1.webp",
    //     "selectNum": 1
    // }],
    categories: [
        {
            name: '美食外卖',
            image_path: 'TB1xmb.PXXXXXb7XpXXXXXXXXXX-186-96.png',
            order: 1
        }, {
            name: '甜品饮品',
            image_path: 'TB1DaUiPXXXXXcUXXXXXXXXXXXX-186-96.png',
            order: 1
        }, {
            name: '果蔬生鲜',
            image_path: 'TB1S7YIPXXXXXawapXXXXXXXXXX-185-96.png',
            order: 1
        }, {
            name: '蜂鸟配送',
            image_path: 'TB1nZzYPXXXXXa1XVXXXXXXXXXX-186-96.png',
            order: 1
        }, {
            name: '商超便利',
            image_path: 'TB1bxJpQFXXXXaBXVXXXXXXXXXX-186-96.png',
            order: 1
        }, {
            name: '品牌馆',
            image_path: 'TB1WuohPXXXXXXuXpXXXXXXXXXX-186-96.png',
            order: 1
        }, {
            name: '小吃夜宵',
            image_path: 'TB1w3YNPXXXXXXKapXXXXXXXXXX-186-96.png',
            order: 1
        }, {
            name: '新店推荐',
            image_path: 'TB1VTz8PXXXXXbJXFXXXXXXXXXX-186-96.png',
            order: 1
        },{
            name: '包子粥店',
            image_path: 'TB19kyFOpXXXXbJapXXXXXXXXXX-186-96.png',
            order: 2
        }, {
            name: '能量套餐',
            image_path: 'TB1Y511OpXXXXbuXFXXXXXXXXXX-186-96.png',
            order: 2
        }, {
            name: '特色面食',
            image_path: 'TB1.ByKOpXXXXb6aXXXXXXXXXXX-186-96.png',
            order: 2
        }, {
            name: '西式快餐',
            image_path: 'TB1zdaIOpXXXXXgapXXXXXXXXXX-186-96.png',
            order: 2
        }, {
            name: '异国料理',
            image_path: 'TB1V8zQPXXXXXXAapXXXXXXXXXX-186-96.png',
            order: 2
        }, {
            name: '麻辣诱惑',
            image_path: 'TB1Afm7OpXXXXaeXFXXXXXXXXXX-186-96.png',
            order: 2
        }, {
            name: '鲜花蛋糕',
            image_path: 'TB1p7rVPXXXXXaaaXXXXXXXXXXX-186-96.png',
            order: 2
        }, {
            name: '全部分类',
            image_path: 'TB1amq7OpXXXXXPXFXXXXXXXXXX-186-96.png',
            order: 2
        }
    ],
    foods: [{
        "id": 1,
        "restaurant_id": 147011301,
        "name": "神奇鸡翅",
        "description": "鸡肉+蔬菜（西兰花、胡萝卜、菜花）",
        "price": 10,
        "image_path": "r1.webp",
        "order_lead_time": 10
    }, {
        "id": 2,
        "restaurant_id": 147011301,
        "name": "黑暗料理",
        "description": "鸡肉+蔬菜（西兰花、胡萝卜、菜花）",
        "price": 100,
        "image_path": "r1.webp",
        "order_lead_time": 10
    }, {
        "id": 3,
        "restaurant_id": 147011302,
        "name": "神奇鸡翅",
        "description": "鸡肉+蔬菜（西兰花、胡萝卜、菜花）",
        "price": 10,
        "image_path": "r1.webp",
        "order_lead_time": 10
    }, {
        "id": 4,
        "restaurant_id": 147011302,
        "name": "黑暗料理",
        "description": "鸡肉+蔬菜（西兰花、胡萝卜、菜花）",
        "price": 100,
        "image_path": "r1.webp",
        "order_lead_time": 10
    }],
    cities: [{
        "cityCode": "513200",
        "cityName": "阿坝",
        "cityNameAlphabet": "aba",
        "cityNameInitial": "ab",
        "selected": "false"
    }, {
        "cityCode": "610900",
        "cityName": "安康",
        "cityNameAlphabet": "ankang",
        "cityNameInitial": "ak",
        "selected": "false"
    }, {
        "cityCode": "652900",
        "cityName": "阿克苏",
        "cityNameAlphabet": "akesu",
        "cityNameInitial": "aks",
        "selected": "false"
    }, {
        "cityCode": "220100",
        "cityName": "长春",
        "cityNameAlphabet": "changchun",
        "cityNameInitial": "cc",
        "selected": "false"
    }, {
        "cityCode": "430700",
        "cityName": "常德",
        "cityNameAlphabet": "changde",
        "cityNameInitial": "cd",
        "selected": "false"
    }, {
        "cityCode": "542100",
        "cityName": "昌都",
        "cityNameAlphabet": "changdu",
        "cityNameInitial": "cd",
        "selected": "false"
    }, {
        "cityCode": "510100",
        "cityName": "成都",
        "cityNameAlphabet": "chengdu",
        "cityNameInitial": "cd",
        "selected": "false"
    }, {
        "cityCode": "130800",
        "cityName": "承德",
        "cityNameAlphabet": "chengde",
        "cityNameInitial": "cd",
        "selected": "false"
    }, {
        "cityCode": "500100",
        "cityName": "重庆",
        "cityNameAlphabet": "chongqing",
        "cityNameInitial": "cq",
        "selected": "false"
    }, {
        "cityCode": "430100",
        "cityName": "长沙",
        "cityNameAlphabet": "changsha",
        "cityNameInitial": "cs",
        "selected": "false"
    }, {
        "cityCode": "532300",
        "cityName": "楚雄",
        "cityNameAlphabet": "chuxiong",
        "cityNameInitial": "cx",
        "selected": "false"
    }, {
        "cityCode": "211300",
        "cityName": "朝阳",
        "cityNameAlphabet": "chaoyang",
        "cityNameInitial": "cy",
        "selected": "false"
    }, {
        "cityCode": "320700",
        "cityName": "连云港",
        "cityNameAlphabet": "lianyungang",
        "cityNameInitial": "lyg",
        "selected": "false"
    }, {
        "cityCode": "450200",
        "cityName": "柳州",
        "cityNameAlphabet": "liuzhou",
        "cityNameInitial": "lz",
        "selected": "false"
    }, {
        "cityCode": "510500",
        "cityName": "泸州",
        "cityNameAlphabet": "luzhou",
        "cityNameInitial": "lz",
        "selected": "false"
    }, {
        "cityCode": "630100",
        "cityName": "西宁",
        "cityNameAlphabet": "xining",
        "cityNameInitial": "xn",
        "selected": "false"
    }, {
        "cityCode": "469037",
        "cityName": "西沙",
        "cityNameAlphabet": "xisha",
        "cityNameInitial": "xs",
        "selected": "false"
    }, {
        "cityCode": "532800",
        "cityName": "西双版纳",
        "cityNameAlphabet": "xishuangbanna",
        "cityNameInitial": "xsbn",
        "selected": "false"
    }, {
        "cityCode": "429004",
        "cityName": "仙桃",
        "cityNameAlphabet": "xiantao",
        "cityNameInitial": "xt",
        "selected": "false"
    }, {
        "cityCode": "440400",
        "cityName": "珠海",
        "cityNameAlphabet": "zhuhai",
        "cityNameInitial": "zh",
        "selected": "false"
    }, {
        "cityCode": "321100",
        "cityName": "镇江",
        "cityNameAlphabet": "zhenjiang",
        "cityNameInitial": "zj",
        "selected": "false"
    }, {
        "cityCode": "440800",
        "cityName": "湛江",
        "cityNameAlphabet": "zhanjiang",
        "cityNameInitial": "zj",
        "selected": "false"
    }, {
        "cityCode": "430800",
        "cityName": "张家界",
        "cityNameAlphabet": "zhangjiajie",
        "cityNameInitial": "zjj",
        "selected": "false"
    }]
}
